#!/bin/bash

export PATH="/usr/local/opt/mysql-client/bin:$PATH"
hh="User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36"
cat dati.php | grep "=" | sed -e 's/\$//g' -e 's/;//g' > dd0
. dd0

cc="IK4LZH"
curl -s -L -H $hh https://www.qrz.com/lookup/$cc > dd1
uu=`grep wc_summary dd1 | awk -F'"' '{print $2}'`; curl -s -L "$uu" > dd2
cat dd2 | sed -e 's/<a/\n/g' -e 's/<\/a>/\n/g' | grep href > dd3
cat dd3 | awk -F'"' '{split($6,a," ");if(index($4,"db//")==0 && length(a[3])>0){split($4,b,"/");print b[5] "," $4 "," a[3] "," a[4] "," $8;}}' > dd4

cat dd4 | awk -F"," '{print "INSERT IGNORE INTO qrz (callsign,inlist) VALUES (\x27"$1"\x27,1);"}' > dd5
cat dd5| mysql -h $myhost -u $myuser -p$mypasswd qso

echo "SELECT callsign FROM qrz WHERE checked=0;" > dd6
cat dd6| mysql -h $myhost -u $myuser -p$mypasswd qso > dd7

# bisogna capire quante volte deve essere reiterata questa funzione
tail -n +2 dd7 | while read cc; do

  echo $cc
  curl -s -L -H $hh https://www.qrz.com/lookup/$cc > dd1
  uu=`grep wc_summary dd1 | awk -F'"' '{print $2}'`; curl -s -L "$uu" > dd2
  cat dd2 | sed -e 's/<a/\n/g' -e 's/<\/a>/\n/g' | grep href > dd3
  cat dd3 | awk -F'"' '{split($6,a," ");if(index($4,"db//")==0 && length(a[3])>0){split($4,b,"/");print b[5] "," $4 "," a[3] "," a[4] "," $8;}}' > dd4

  cat dd4 | awk -F"," '{print "INSERT IGNORE INTO qrz (callsign) VALUES (\x27"$1"\x27);"}' > dd5
  ff=`cat dd4 | wc -l`
  echo -e "UPDATE qrz SET webtab=$ff WHERE callsign='$cc';" >> dd5
  ff=`grep -w IK4LZH dd4 | wc -l`
  if [ $ff -ne 0 ]; then
    echo "... IK4LZH present"
    echo -e "UPDATE qrz SET outlist=1 WHERE callsign='$cc';" >> dd5
  fi
  echo -e "UPDATE qrz SET checked=1 WHERE callsign='$cc';" >> dd5
  echo -e "UPDATE qrz SET inqso=1 WHERE callsign='$cc' and EXISTS (SELECT callsign FROM qso where callsign='$cc');" >> dd5

  cat dd5 | mysql -h $myhost -u $myuser -p$mypasswd qso
  
done
